package com.example.myapplication4.face

import android.content.Context
import android.graphics.Bitmap
import android.util.Log
import com.google.mediapipe.framework.image.BitmapImageBuilder
import com.google.mediapipe.tasks.core.BaseOptions
import com.google.mediapipe.tasks.vision.core.RunningMode
import com.google.mediapipe.tasks.components.containers.Embedding
import com.google.mediapipe.tasks.vision.imageembedder.ImageEmbedder
import com.google.mediapipe.tasks.vision.imageembedder.ImageEmbedder.ImageEmbedderOptions
import com.google.mediapipe.tasks.vision.imageembedder.ImageEmbedderResult
import javax.inject.Inject

class FaceNetModel @Inject constructor(private val context: Context) {
    private var imageEmbedder: ImageEmbedder? = null
    private val outputVectorSize = 512

    init {
        try {
            val baseOptions = BaseOptions.builder()
                .setModelAssetPath("facenet.tflite")
                .build()

            val options = ImageEmbedderOptions.builder()
                .setBaseOptions(baseOptions)
                .setRunningMode(RunningMode.IMAGE)
                .build()

            imageEmbedder = ImageEmbedder.createFromOptions(context, options)
            Log.d("FaceNetModel", "MediaPipe ImageEmbedder loaded successfully for FaceNet.")
        } catch (e: Exception) {
            Log.e("FaceNetModel", "Failed to load MediaPipe ImageEmbedder for FaceNet: ${e.message}", e)
            imageEmbedder = null
        }
    }

    fun getFaceEmbedding(faceBitmap: Bitmap): FloatArray? {
        if (imageEmbedder == null) {
            Log.e("FaceNetModel", "MediaPipe ImageEmbedder is not initialized.")
            return null
        }

        try {
            val mpImage = BitmapImageBuilder(faceBitmap).build()

            val results: ImageEmbedderResult? = imageEmbedder?.embed(mpImage)

            val embeddingsList: List<Embedding>? = results?.embeddingResult()?.embeddings()
            val embeddings = embeddingsList?.firstOrNull()?.floatEmbedding()

            if (embeddings != null) {
                Log.d("FaceNetModel", "Face embedding generated: ${embeddings.size} dimensions.")
                return embeddings
            } else {
                Log.e("FaceNetModel", "No embeddings generated by MediaPipe ImageEmbedder.")
                return null
            }
        } catch (e: Exception) {
            Log.e("FaceNetModel", "Error running MediaPipe ImageEmbedder: ${e.message}", e)
            return null
        }
    }

    fun close() {
        imageEmbedder?.close()
        imageEmbedder = null
        Log.d("FaceNetModel", "MediaPipe ImageEmbedder closed.")
    }
}